### ISSUE TITLE
Your pretrained weights have a problem

### ISSUE THREAD

**Issue by MCDM2018** [Vandermode/ERRNet#1]
A few minute ago i did test on CEIL Synthetic dataset with your pre-trained weights.
But, When i check the results, As well as other quantitative results are low, all of inferences are black.

**Comment by Vandermode** [comment]
Thank you for your feedback. Are you sure you have loaded the model appropriately?  
In testing, you should see the information presented as follow: ```Resume from epoch 60, iteration ...```

I remember a sanity check has been conducted before uploading the pretrained weights.

If you still cannot reproduce the results, I'll check it later.

Thanks

**Comment by MCDM2018** [comment]
@Vandermode  "Thank you for your feedback. Are you sure you have loaded the model appropriately?" Yeah sure.  Actually, I was trying to compare trained weights from scratch with pre-trained  weights.
Although trained weights from scratch works well, pre-trained weights is not.
But i cannot  exclude a chance that i have a mistake. 
So anyway,  i will re-check. 
Thank you for answer.

**Comment by MCDM2018** [comment]
@Vandermode  Hi. i did check why it didn't work well. It was my PC problem. your pre-trained weights work well in my server computer.
