### ISSUE TITLE
The Google Drive link is not found

### ISSUE THREAD

**Issue by DreamtaleCore** [Vandermode/ERRNet#11]
Hi，
The google drive of pretrained model is not available, could you please check that link?

Best regards

**Comment by Vandermode** [comment]
Hi, Thank you for your feedback. I'll fix this issue soon.

**Comment by Somyarani1113** [comment]
@Vandermode I am not able to access the gdrive. Could you please check ?

**Comment by Vandermode** [comment]
The broken link has been fixed; the access right has been set to be viewed only to avoid malicious deletion.
