### ISSUE TITLE
Questions about evaluation on Real20

### ISSUE THREAD

**Issue by vinthony** [Vandermode/ERRNet#12]
Hi, thanks for your awesome work.

I want to evaluate your model on Real20. 

However, the resolution of real20 dataset is too large for prediction.

Which size are you use to evaluate?

**Comment by Vandermode** [comment]
Hi, for each image, I resize the short edge to 512 while keeping the aspect ratio fixed. You can mannually process Real20 images based upon ```__scale_width``` and ```__scale_height``` provided in ```data/reflect_dataset.py``` (see line 50-56 of ```paired_data_transforms```)

**Comment by vinthony** [comment]
Thanks!
