### ISSUE TITLE
Pretrained model from Google Drive is not found

### ISSUE THREAD

**Issue by nekojan** [Vandermode/ERRNet#13]
404 The requested URL was not found on this server.

**Comment by Vandermode** [comment]
Please refer to README.md

**Comment by nekojan** [comment]
From README.md

> Download our pretrained model from Google Drive and move errnet_060_00463920.pt to checkpoints/errnet/.

When click on the Google Drive link, I get 404 The requested URL was not found on this server.

**Comment by nekojan** [comment]
Oh, it's on the top of the README.MD. Got it now. Thanks!
