### ISSUE TITLE
Do  90 real-world training images from Berkeley real dataset have to be cropped to 224x224  When training the model for aligned model?

### ISSUE THREAD

**Issue by jinx2018** [Vandermode/ERRNet#14]
hey! When i train the model,it reports error like this `line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last)` . I wonder is this attribute to the data sample size problem?
  Actually, The size from three sets for training are 
- VOC2012 . 224x224
- testdata_reflection_synthetic_table2 . 224 x224
- real_train . inconsistent ， Mostly larger than 224

Do I need to center-crop 90(actually 89) samples in real dataset to 224x224 to train this model??

Thank you !

**Comment by Vandermode** [comment]
No, I do not think you need to do so. 

I guess you might use a batch size > 1, which triggers this bug. 

In fact, in my implementation, all the images have been preprocessed to 224x224 online, regardless of their original size. You might need to take a look at ```paired_data_transforms``` in ```data/reflect_dataset```.

**Comment by jinx2018** [comment]
Ok, I see. thanks for your help 😀😀

**Comment by jinx2018** [comment]
Additionally, anyway when you test the model on largers size image samples(suxch as the demo your put on the readme home page ), how do you manage to apply the model trained on 224x224 to images with larger sizes ?

**Comment by Vandermode** [comment]
In fact, fully-convolutional network can process images with arbitrary size.
