### ISSUE TITLE
CUDA outofmemory error。

### ISSUE THREAD

**Issue by 1210264601** [Vandermode/ERRNet#2]
HI，thanks to your great work.
i want to test one image, and save the result. but meet the error:
![image](https://user-images.githubusercontent.com/11661034/60006001-333cc600-96a2-11e9-996e-d41adbd6f4f3.png)

why test one image need so big memory? or somthing wrong else?

**Comment by Vandermode** [comment]
Which size of image you tested? Our network is very large, and can only process a 512x768 image in a NVIDIA GTX 1080Ti GPU in inference. If you wish to process a large image, perhaps you should use the sliding-window strategy.

**Comment by 1210264601** [comment]
OK,  thanks.
