### ISSUE TITLE
unaligned datas

### ISSUE THREAD

**Issue by Carlyx** [Vandermode/ERRNet#20]
Hi, I just trained the errnet with the aligned datas follow the second part (Playing with aligned data) on GitHub. And The effect is good on aligning datasets. And could you give me some advice on how to utilize misaligned training data?

**Comment by Vandermode** [comment]
Hi, Thank you for your interest. I'll update the README.md for unaligned data soon...

**Comment by Carlyx** [comment]
Thank you for your reply. Your work is awesome， and I will keep paying attention to it.

**Comment by Vandermode** [comment]
The code for unaligned data has been uploaded..

**Comment by Carlyx** [comment]
Thank you very much. got it.
