### ISSUE TITLE
Pascal VOC dataset

### ISSUE THREAD

**Issue by masqueradecode** [Vandermode/ERRNet#21]
Your work is very great. But we have some questions about Pascal VOC dataset.  When we train, we don't find the ground truth of Pascal VOC dataset.  Do we miss something, or how do you generate the GT of Pascal VOC?

**Comment by Vandermode** [comment]
The GT of Pascal VOC dataset? I simply crop the center region (224x224) of the images listed in ```VOC2012_224_train_png.txt```

**Comment by masqueradecode** [comment]
I read your code again.  I only saw the images without reflection effect in Pascal VOC , and I didn't see the images with reflection last week.    Now I find the way to generate the images with reflection (class ReflectionSythesis_1).   Thank you for your help.
