### ISSUE TITLE
Can it be used to remove watermarks?

### ISSUE THREAD

**Issue by zxq2233** [Vandermode/ERRNet#22]

**Comment by Vandermode** [comment]
Interesting idea, which kind of watermarks you would like to remove? 
In my opinion, in most situations, the watermark removal task is more close to a image inpainting task rather than the reflection removal task

**Comment by zxq2233** [comment]
@Vandermode Is it suitable for translucent watermark removal?

**Comment by Vandermode** [comment]
please upload an example image if you want to try.
