### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by Carlyx** [Vandermode/ERRNet#24]
Hi, when I reproduced your results（only with aligned data）, I found that the loss for the first ten times fell very fast, and the subsequent decrease was slow.  For example, VGG dropped from 4 to 1.81 (1.31 after 60 iterations) and Ipixel dropped from 0.021 to 0.0094 (0.09 after 60 iterations) after only 15 repetitions. 
I also tested testdata_reflection_synthetic_table2 with the 15-iterations model and got relatively good visual effects. Is this normal? Or something i did wrong.

**Comment by Carlyx** [comment]
I also found higher CPU usage when I was training on Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-74-generic x86_64) with TITAN RTX.  Is there some part of the calculation using CPU parallel computing?

**Comment by Vandermode** [comment]
For your first question, in practice, we train the model with much long time to ensure the convergence, though it's possible to achieve similar performance with less training time. 

For your second question, yes, the data loading and transformation are performed in CPU parallel computing.

**Comment by Carlyx** [comment]
Ok.  Thanks!
