### ISSUE TITLE
sliding-window strategy

### ISSUE THREAD

**Issue by sjf18** [Vandermode/ERRNet#25]
hi, thanks for your great work,  when i test a large image, i got  oom error. 
And i have seen the old issues,  do you provide sliding-window strategy in your code?

**Comment by Vandermode** [comment]
Currently not, but the functionality can be simply added by refering to ```forward_chop``` function implemented in
```
https://github.com/thstkdgus35/EDSR-PyTorch/blob/a90b54d1b7f8ee780920e2ccd30692ab8e783f46/src/model/__init__.py#L105
```
