### ISSUE TITLE
Regarding synthetic training dataset (7,643 images) for reflection removal

### ISSUE THREAD

**Issue by rohansinghjain** [Vandermode/ERRNet#26]
Hi,

How do I save the synthetic training dataset for reflection removal generated using PASCAL VOC2012 images locally? Is it being generated on the fly? Could you please provide code pointers / provide the synthetic training dataset? (mixed, background and reflection layer images).

Thanks
Rohan

**Comment by Vandermode** [comment]
yes, the synthetic data is generated on-the-fly. please check https://github.com/Vandermode/ERRNet/blob/c7d786f4d94e8ac1f56fa3de75b53cbe9079e527/data/reflect_dataset.py#L92
for more detail

**Comment by rohansinghjain** [comment]
Thanks for your prompt reply! 
I have one more query though. The VOC2012_224_train_png.txt file lists 15,287 images and the training dataset consists of half of 15,287 i.e. 7,643 images. Is the split for the reflection and transmission layer images random? Can I split the 15,287 images into two equal sets randomly : transmission layer and reflection layer, and go on to combine one image from each set to get 7,643 images containing reflection ?
