### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by Carlyx** [Vandermode/ERRNet#28]
Hi, I've noticed that your code runs reset () after each epoch, but this function is only for CEIL data, and there is no reset for real20. I'd like to ask a related question about this. 
If I use all my data, just like real20, it has been synthesized in a fixed order, whether it is necessary to reset(), whether it is necessary or optional.
@Vandermode

**Comment by Vandermode** [comment]
Hi, sorry for the late reply. The reset flag is only used for synthetic data to select different sources of transmission and reflection layer, so you should ignore the reset flag when using real data
