### ISSUE TITLE
Slightly different architecture

### ISSUE THREAD

**Issue by MrYoman** [Vandermode/ERRNet#29]
Hi, I've noticed that the implemented architecture of DRNet is slightly different from the architecture described on the Figure 2 in the paper [https://arxiv.org/pdf/1904.00637.pdf](https://arxiv.org/pdf/1904.00637.pdf):
(1) in the code SELayer consists of Linear-ReLU-Linear-Sigmoid layers, but in the paper convolutional layers are drawn instead of Linear
(2) in the code deconvolution+convolution layers are used after residual blocks, but  in the paper only a convolutional layer is drawn.

**Comment by Vandermode** [comment]
Hi, Thank you for pointing this out. 
As for you questions:
1. the linear layer can also be replaced by a 1x1 convolution layer - they are equivalent as the spatial size of the input feature map is 1x1
2. deconvolution can be viewed as a convolution with fractional stride (e.g. 1/2), but you are right, I just miss drawing an extra de/convolution layer.

**Comment by MrYoman** [comment]
Thank you for your answer!
