### ISSUE TITLE
Cuda runnign OOM

### ISSUE THREAD

**Issue by Dayananda-V** [Vandermode/ERRNet#3]
Dear Team,

Am facing "Cuda running OOM" problem while runing test few sample, am not able to solve this problem using "--gpu_ids 0,1" , please help me to solve this problem.

![image](https://user-images.githubusercontent.com/13178240/60085502-131b0e80-9757-11e9-801a-07a324c32bd9.png)

**Comment by Vandermode** [comment]
@Dayananda-V Please refer to the issue #2 to see if you could solve the problem

**Comment by Dayananda-V** [comment]
@Vandermode 

am testing https://drive.google.com/drive/folders/1NYGL3wQ2pRkwfLMcV2zxXDV8JRSoVxwA this dataset, even with this same GPU configuration consuming much more memory, really not able to solve this problem.

**Comment by Vandermode** [comment]
Please downsample the image size, or use sliding-window strategy instead.

**Comment by Timmmmmms** [comment]
I'm a freshman in this field. My GPU is GTX1080ti, Can you give me some advice how to downsample the image size, or sliding-window.

**Comment by Vandermode** [comment]
@Timmmmmms , please refer to ```https://stackoverflow.com/questions/273946/how-do-i-resize-an-image-using-pil-and-maintain-its-aspect-ratio```
