### ISSUE TITLE
KeyError: 'real' when batch size > 1

### ISSUE THREAD

**Issue by Ir1d** [Vandermode/ERRNet#31]
Hi, it seems that this happens when the data in a training batch isn't from the same dataset. (caused by the extra 'real' tag in `train_dataset_real`)
Did you train with only batch size=1? In my case it takes 3GB and I think it could be faster with larger batch size.

**Comment by Ir1d** [comment]
Also, it seems that in `./options/errnet/base_options.py`, `torch.cuda.set_device(self.opt.gpu_ids[0])` shows that only the first of the gpu ids is used, the model couldn't train with multiple gpus right?

**Comment by Ir1d** [comment]
Also, I'm getting CUDA OOM on testset `testdata_real20`. The first input image is  of size `3, 1935, 2942`.. is this correct?

**Comment by Vandermode** [comment]
1. During training, we randomly select an image either from the synthetic dataset or the real dataset. I remember it costs >8G GPU in training stage. 

2. Multiple gpus are not used as the batch size is 1, but you can try large batch size using multiple gpus (with some code modifications)

3. You can process the real images in a sliding window strategy or just simply resize the short edge of images to 512 to avoid OOM issue.

I hope these are helpful for you.

**Comment by Ir1d** [comment]
@Vandermode thanks, but I still get OOM from time to time (after several epochs) even though I downsampled the images, its quite werid :joy:

> it would cost >8G GPU in the training stage.
Did you center crop the image to 224x224 or use the original image from VOC2012?

**Comment by Ir1d** [comment]
@Vandermode apologize for interrupting again, but I couldn't reproduce the trained model. After training for 40 epochs, I get psnr of 20.5 in Real20 dataset. I've also tested the pretrained model you released and it achieves 22.8

I diffed my edits and there was no important change to the code. Did you train with input size of 1x3x224x224? I noticed that the GPU mem usage is less than 4G (3474M) even I enable discriminator loss.

**Comment by Vandermode** [comment]
Did you enable hyper-column feature in training?
Which which system and pytorch version you used?

**Comment by Ir1d** [comment]
I ran this command `python train_errnet.py --name errnet --hyper`, and I used ubuntu 18.04 and pytorch 1.2.0

**Comment by Vandermode** [comment]
I run the released code, in the training stage, it costs about 4G GPU memory, so you are right. 

As for the data, first, I used the cropped (224x224) images from VOC2012 dataset. If you would like to use large size, you need to modify or disable ```paired_data_transforms``` in ```data/reflect_dataset```. 

Besides, you should check the final performance in epoch 60 to see whether you can reproduce the result.

**Comment by Ir1d** [comment]
Thank you so much! I'll carefully check my code and wait till epoch 60! :heart: 

btw, did you crop the images from VOC before training or during training?

**Comment by Vandermode** [comment]
I crop the images before training (by following the CEILNet paper), though I feel it does nothing to the model performance. 

 ```paired_data_transforms``` would also transform (resize and crop) images during training.

**Comment by Vandermode** [comment]
Btw, the short edge of  90 real images has been resized to 512 before training. I guess it might impact the performance, if you evaluate on the resized version of 20 real images.

**Comment by Ir1d** [comment]
Thanks for letting me know! I didn't realize that the training images were also resized. I noticed that the original real20 dataset causes OOM during testing and resized them to 1/4 size. I'll retrain the model after resizing them to 512.

**Comment by Ir1d** [comment]
Hi, I've resized all the images in real20 to 512.. And the trained model achieves PSNR of 24.5.. I also tested your released model but it got 22.83.

However, I'm still a bit curious why I got so much better PSNR..

@Vandermode Did you evaluate on the original size real20 dataset? I think current code doesn't support cropping the test image into patches, so I'm not sure whether you tested on the original size images.

**Comment by Vandermode** [comment]
The results in the paper: both training and evaluation are performed in the resized version of real images. 

Is your reproduced model (24.5) trained on the original size while evaluating on the resized images?

**Comment by Ir1d** [comment]
Thanks! 
I believe I trained on the resized images and tested on the resized images. I'll have to check again whether I left some test images in the training set :joy:

**Comment by Ir1d** [comment]
:heart:  Thanks! I trained again (made sure that I didn't also train on the test set) and achieved around PSNR of 22 at epoch 55. I think it's fairly acceptable considering the randomness during training.

**Comment by Rachel-kk** [comment]
> @Vandermode apologize for interrupting again, but I couldn't reproduce the trained model. After training for 40 epochs, I get psnr of 20.5 in Real20 dataset. I've also tested the pretrained model you released and it achieves 22.8
> 
> I diffed my edits and there was no important change to the code. Did you train with input size of 1x3x224x224? I noticed that the GPU mem usage is less than 4G (3474M) even I enable discriminator loss.
> 
> ![image](https://user-images.githubusercontent.com/10709657/82184499-51df2780-991a-11ea-848c-52188fae0655.png) ![image](https://user-images.githubusercontent.com/10709657/82184518-5d325300-991a-11ea-9ee7-d69a2ac5c676.png)

Hi, Please how did you resize the real20 dataset druing testing?
