### ISSUE TITLE
do i need to make folder "/media/kaixuan/DATA/Papers/Code/Data/Reflection/VOCdevkit/VOC2012/PNGImages"

### ISSUE THREAD

**Issue by semi-kim** [Vandermode/ERRNet#35]
/ERRNet/data/image_folder.py", line 33, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: /media/kaixuan/DATA/Papers/Code/Data/Reflection/VOCdevkit/VOC2012/PNGImages is not a valid directory

**Comment by Vandermode** [comment]
No, change it to your custom address
