### ISSUE TITLE
core dumped reported when test mobile camera image 

### ISSUE THREAD

**Issue by Dayananda-V** [Vandermode/ERRNet#4]
Dear team, 

i capture Nexus 6P phone with less resolution image and same image use to evaluate model, but encounter Abort(core dumped) with following error on cpu, but model able to run smoothly on other data set. Any precondition or image process need to follow for own test image?

![image](https://user-images.githubusercontent.com/13178240/60158975-c7786b80-980f-11e9-98fc-70b515d65803.png)

**Comment by Vandermode** [comment]
Perhaps you should ensure the image size is the integral multiple of 2.

**Comment by Dayananda-V** [comment]
yes, with integral multiple of 2 its working, but more than 1.2Mb size of image core dump still present.

**Comment by Vandermode** [comment]
Not exactly sure what's the problem. But at least you can solve this issue by sliding-window strategy if you wish to process such large image.
