### ISSUE TITLE
About the suppl. material

### ISSUE THREAD

**Issue by luqiang360** [Vandermode/ERRNet#5]
Could you release your supp? I read your paper and you refer the suppl. material, but I searched the [CVPR 2019 Open Access Repository](http://openaccess.thecvf.com/CVPR2019_search.py) and the google website I cannot find the suppl, look forward to your reply.

**Comment by Vandermode** [comment]
Hi, Thanks for your interests in our work. We will release the suppl. and let you know soon.

**Comment by Vandermode** [comment]
Hello, our suppl. material and poster are now accessible at Google Drive, please refer to readme for details.
