### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Timmmmmms** [Vandermode/ERRNet#6]
Dear Team,
         How to fix the multiple workers on windows? I run that code on windows, and have this error when I set the nThread=8. It's Ok for 0, but the code run too slow and broke down. How to fix it ?

**Comment by Vandermode** [comment]
Sorry, I cannot help you in this problem, as I always develop in ubuntu, without any prior experience on windows.
