### ISSUE TITLE
ImportError: cannot import name 'imresize'

### ISSUE THREAD

**Issue by aditya98ak** [Vandermode/ERRNet#9]
I was trying to run ERRNet on my machine but was getting this error again and again.
I'm running 
python test_errnet.py --name errnet -r --icnn_path checkpoints/errnet/errnet_060_00463920.pt --hyper
According to the official document, 'imresize' is removed in SciPy 1.3.0.

**Comment by Vandermode** [comment]
Yes, you are right, imresize is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
Any version < 1.3.0 should work in this implementation.
For SciPy version >= 1.3.0, you can use ```skimage.transform.resize``` or ```skimage.transform.rescale``` instead.

**Comment by aditya98ak** [comment]
I've updated this, may I send a PR for the same?
@Vandermode
